"use server"

import { db } from "@/lib/db";
import { productCategory } from "@/lib/schema";
import { revalidatePath } from "next/cache";
import { requireSession } from "./with-auth";
import { or, eq, ilike } from "drizzle-orm";

export async function getProductCategories() {
    const authResult = await requireSession();
    if (authResult.status === "error") {
        return { status: "error" as const, message: "Unauthorized" };
    }

    try {
        const categories = await db.query.productCategory.findMany({
            orderBy: (model, { asc }) => [asc(model.name)],
            with: {
                products: {
                    columns: { id: true }
                }
            }
        });

        const mapped = categories.map(c => ({
            ...c,
            _count: { products: c.products.length }
        }));

        return { status: "success" as const, data: mapped };
    } catch (error) {
        console.error("Failed to fetch product categories:", error);
        return { status: "error" as const, message: "Failed to fetch categories" };
    }
}

export async function createProductCategory(data: { name: string }) {
    const authResult = await requireSession();
    if (authResult.status === "error") {
        return { status: "error" as const, message: "Unauthorized" };
    }

    try {
        // Generate slug from name
        const slug = data.name
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/(^-|-$)/g, "");

        const existing = await db.query.productCategory.findFirst({
            where: (model) => or(
                ilike(model.name, data.name),
                eq(model.slug, slug)
            )
        });

        if (existing) {
            return { status: "error" as const, message: "A category with this name already exists" };
        }

        const [category] = await db.insert(productCategory).values({
            id: crypto.randomUUID(), // Assuming id is manually set or generated by db
            name: data.name,
            slug
        }).returning();

        revalidatePath("/store");
        return { status: "success" as const, data: category };
    } catch (error) {
        console.error("Failed to create product category:", error);
        return { status: "error" as const, message: "Failed to create category" };
    }
}

export async function deleteProductCategory(categoryId: string) {
    const authResult = await requireSession();
    if (authResult.status === "error") {
        return { status: "error" as const, message: "Unauthorized" };
    }

    try {
        await db.delete(productCategory).where(eq(productCategory.id, categoryId));

        revalidatePath("/store");
        return { status: "success" as const, message: "Category deleted" };
    } catch (error) {
        console.error("Failed to delete product category:", error);
        return { status: "error" as const, message: "Failed to delete category" };
    }
}
